### ISSUE TITLE
Problems controlling the bulbs

### ISSUE THREAD

**Issue by Strutten** [stenehall/homebridge-ikea#11]
Hi!

I've gotten some excellent help from stenehall both to get the homebridge and the plugin working, but registered here in order to do it all by the book!

I am now able to start homebridge with homebridge-ikea without any errors, and I am able to identify all IKEA-products in the home app. The only kink is that nothing happens with the bulbs when I try to control them via the home app. The Ikea-app still works as expected. I am sorry for my lack of programming knowledge, but I could get a push in the right direction that might help others as well!

/Martin

**Comment by mgntrn** [comment]
Hm, same issue here! The only output in the terminal is `4.00`

**Comment by stenehall** [comment]
There's a debug setting in your `config.json` that you can enable. If you add `debug: true` to your config for `homebridge-ikea` you'll get a lot more information of what's going on when starting `homebridge`.

It should give you the actual call to the `coap` client. They should look something like this:

```
/path/to/plugin/coap-client-darwin -u "Client_identity" -k "<your' psk>" -m get coaps://192.168.1.123/15001/65537
```

if you try to run that command what happens?

If you try to turn on the lamps from homekit while running in debug mode you should see the commands that's being run. If you run them outside of homebridge, what happens?

**Comment by mgntrn** [comment]
This is the output of the debug mode when I try to turn on/off my lights in the Home app:

```
[4/24/2017, 10:19:18 AM] [Gateway] [Lamp 1] Setting brightness of 255 for 65541
[4/24/2017, 10:19:18 AM] [Gateway] [Lamp 1] echo '{ "3311" : [{ "5851" : 255} ] }' | /usr/local/lib/node_modules/homebridge-ikea/bin/coap-client-darwin -u "Client_identity" -k "<psk>" -m put coaps://192.168.1.237/15001/65541 -f -
4.00
[4/24/2017, 10:19:22 AM] [Gateway] [Lamp 1] Setting brightness of 0 for 65541
[4/24/2017, 10:19:22 AM] [Gateway] [Lamp 1] echo '{ "3311" : [{ "5851" : 0} ] }' | /usr/local/lib/node_modules/homebridge-ikea/bin/coap-client-darwin -u "Client_identity" -k "<psk>" -m put coaps://192.168.1.237/15001/65541 -f -
4.00
```

Where <psk> is my actual psk. Also, the output always says I'm controlling 'Lamp 1', even though I'm trying to control Lamp 2, 3 or 4. But id (`65541`) is different depending to the bulb I'm trying to control.

**Comment by mgntrn** [comment]
When I execute this, I can actually control the bulb:

```
/usr/local/lib/node_modules/homebridge-ikea/bin/coap-client-darwin -u "Client_identity" -k "<psk>" -m put -e '{ "3311" : [{ "5851" : 0} ] }' coaps://192.168.1.237/15001/65541

/usr/local/lib/node_modules/homebridge-ikea/bin/coap-client-darwin -u "Client_identity" -k "<psk>" -m put -e '{ "3311" : [{ "5851" : 255} ] }' coaps://192.168.1.237/15001/65541
```

Update:
Ah well, I see there's been a version bump in the meantime. The commands have changed, but still don't work. When I move the -e parameter before the protocol call it works, like above.

**Comment by stenehall** [comment]
So it's still broken for you even with the updated `-e`? Weird. I'll do yet another bump and move the payload.

**Comment by mgntrn** [comment]
Yes, that's correct. I quickly modified the code to a working version, for me at least. You probably shouldn't use my modifications because it's a quick draft, but in this way it works, so you can use the diff to see where I moved it.

**Comment by stenehall** [comment]
Bumped version, please have a go with it.

Sorry, were to fast and pushed my changes before seeing your PR.

**Comment by mgntrn** [comment]
Awesome, it works! 😄

**Comment by stenehall** [comment]
Nice :)

**Comment by stenehall** [comment]
Would you mind closing this issue if you're happy with the solution.

**Comment by Strutten** [comment]
Of course! Thank you!
