### ISSUE TITLE
Error  Loading Plugin

### ISSUE THREAD

**Issue by talkaboutdesign** [stenehall/homebridge-ikea#12]
How do I bypass this error?

ERROR LOADING PLUGIN homebridge-ikea:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by stenehall** [comment]
This looks like you have a to old version of node. If you write `node -v` what does it give you? You need at least `v0.7.6` for this plugin to work.

**Comment by talkaboutdesign** [comment]
Fixed Node version. Now the issue is this: 

```
[4/23/2017, 7:53:22 PM] Loading 1 platforms...
[4/23/2017, 7:53:22 PM] [Gateway] Initializing Ikea platform...
(node:4598) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token v in JSON at position 0
(node:4598) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by stenehall** [comment]
It definitly looks like you have a missing `,` or an `,` in your config file. Make sure it's [valid json](https://jsonformatter.curiousconcept.com/)

**Comment by stenehall** [comment]
Did you manage to get this working?

**Comment by Honason** [comment]
With Node 7.10.0 I get the same error, and config.json file is a valid JSON.

**Comment by stenehall** [comment]
What version of homebridge-ikea are you trying? Could you please remove your PSK key and share your config.json?

**Comment by Honason** [comment]
I am using homebridge-ikea 0.4.0, and this is the config.json. Thanks for your time!

``` json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "platforms": [{
        "platform": "Ikea",
        "name": "Gateway",
        "ip": "192.168.1.11",
        "psk": "x"
    }]
}
```

**Comment by stenehall** [comment]
Very weird, it works just fine for me. I'll see if I can add some more debug information to the plugin.

**Comment by Honason** [comment]
Hi Johan, my bad, I was using wrong IP address of my gateway.
