### ISSUE TITLE
Does the plugin expose the Tradfri Dimmer as an HomeKit accessory?

### ISSUE THREAD

**Issue by brotkasten87** [stenehall/homebridge-ikea#19]
Hello,

I wonder if it's possible to expose the Tradfri Dimmer dial as an HomeKit dimmer accessory?
That would be awesome because it would allow to use the dimmer for various functions like brightness, volume (of connected speakers) and so on.

Thanks in advance!

**Comment by jannemann** [comment]
As of my understanding, it is not possible at the moment. The commands from the remote control units are directly sent to the bulbs. Unfortunately, these commands are not relayed by the hub to any listening http client like this plugin is.

**Comment by brotkasten87** [comment]
Alright, thanks for the information.

**Comment by stenehall** [comment]
That's correct. Atm I've not seen anyone able to actually expose the dimmer. I'll close this.
