### ISSUE TITLE
Allow fine adjustment of colors

### ISSUE THREAD

**Issue by jannemann** [stenehall/homebridge-ikea#4]
TRÅDFRI only does allow you to choose between 3 different colors. It would be nice to have finer grained control to the color.

**Comment by stenehall** [comment]
You're right in that TRÅDFRI at the moment only allow you to pick 3 different colors. I've been considering droping the "kelvin" implementation and just go with color 1,2,3 as a setting. Sadly there's not great homekit support for naming those colors if I were to change to that setup, or I've at least not found it.

**Comment by shoghicp** [comment]
I tried doing this and the leds didn't let you do that fine-grained control... but still a bit more than IKEA.

Philips Hue does stuff with RGB colors, maybe we can go with that?

**Comment by stenehall** [comment]
Apparently the lamps actually support the entire range between 2200 and 4000 Kelvin. It's fixed now.

**Comment by stenehall** [comment]
Since we're now supporting fine grained 2200 to 4000 kelvin I'll consider this resolved. Feel free to open another issue if you have further ideas.
