### ISSUE TITLE
Support for dimmer

### ISSUE THREAD

**Issue by iCarl** [stenehall/homebridge-ikea#6]
Will there be support for the Ikea dimmer?

**Comment by stenehall** [comment]
As we're not talking directly to any of the Ikea hardware, except the Gateway, there won't be any support for any of the remotes. The dimmer will work with your lamps but not with homebridge. If you change settings on one of your lamps using the dimmer it'll be out of sync for a little while until your homekit app have fetched its state.

**Comment by iCarl** [comment]
Ok, thnaks!
