### ISSUE TITLE
utils.js cmd

### ISSUE THREAD

**Issue by JoergPfe** [stenehall/homebridge-ikea#9]
I think there´s something broken with the cmd for brightness control:

`var cmd = ``echo '{ "3311" : [{ "5851" : ${brightness}} ] }' | ${put(config)}${id} -f -`

which will turn into:
`echo '{ "3311" : [{ "5851" : 1} ] }' | /usr/local/lib/node_modules/homebridge-ikea/bin/coap-client-darwin -u "Client_identity" -k "xxxxxxxxxx" -m put coaps://192.168.0.30/15001/65538 -f -`

In my case the command is not working. 
With following cmd it will work (running in terminal):

`/usr/local/lib/node_modules/homebridge-ikea/bin/coap-client-darwin -m put -u "Client_identity" -k "xxxxxxxxxx" -e '{ "3311": [{ "5851": 1 }] }' "coaps://192.168.0.30/15001/65538"`

Any idea to fix this locally on my side?

**Comment by stenehall** [comment]
the echo solution should work on any system, at least all I've tried. What operating system are you running?

**Comment by stenehall** [comment]
I pushed `v0.3.1` rewriting the calls. No point in having the echo solution, especially if it might cause problems for people. Please let me know if it solves the problem for you.

**Comment by JoergPfe** [comment]
Thanks. I will test it soon and give feedback.

**Comment by stenehall** [comment]
Any updates on this? Everything working now? If so would you mind closing this issue?

**Comment by JoergPfe** [comment]
changed from MacOS to rPi.

Works for me now. Thanks a lot
